language: node_js
node_js:
- '10'
deploy:
  api_key:
    secure: RpOT6crHPacKppksiv9V6pQFP6T+mlCeZivXHfNRM3SNdj8HIV/4dFRcJAYftJ5+f22nHArYI/h1sHdf2d7OHCUncFramOO6FlbLOFw1HdhKRXN9vzZ896Uw5B50AUDzKblR5dPaQoZxjmxPoZWDtWlAw+9GeLFh9dryCpDwyBdIHrtwkXRUEHT+WZi8Ng6x/kB+ifmapQKHb5aD5Xg4Dx5qQFbbS0vcZOhart5JfSOqsBNrK5lb2c8vrSiZXf2IcJE5InXy/78Z4X/oKHS0N3wFzVfxXtmb3VL+tS37Y4A68eca0MFw218yiIEgMAoxZTfxk+gH2BFxHx/feO2ZaSmUyi4gfXUTSvIQ9vYqRQ2pp0WHMNgeJELu53M4SEGpgz5EJ7ZzjWjH3njicoZXcBfpgZrwSjgo7xYksEKlp3auwbNRhQNMcHv2pI0e+qQfgeYk47Rqv9tG7dEa+m46XwWjvRJMMNSRvavUxP1Ok4BEG+v9XFGygTVYZRNRaG9JCtv2IGeU/U894kKNBXqBfBbB8PDP3tGjdY5t1Vbzgxk6rjS5uTNWCewOQ9NYAVGzXL519wa9b51Lr6HFW5mp/YFF9BwD9Wupcxi5pmPpORaO6mdDQ7KSRsRiPigzFN9LKDkTFfYUG9Gq+5ZchxwXcwzw4ranO0KbwmSXtVGafuU=
  email: julian@dotcore.co.il
  provider: npm
  skip_cleanup: true
  on:
    tags: true
script:
- npm test
