name: test
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 18.x
          - 20.x
          - 22.x
        react-version:
          - ^16.8.0
          - ^17.0.0
          - ^18.0.0

    steps:
      - uses: actions/checkout@v5

      - uses: browser-actions/setup-firefox@latest

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      # help the linter
      - name: Install example dependencies
        working-directory: ./examples
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Install react
        run: npm install --no-save react@${{ matrix.react-version }} react-dom@${{ matrix.react-version }}

      - name: Test
        uses: nick-invision/retry@v3 # tests are somewhat flakey
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_SERVICE_NAME: github
          COVERALLS_GIT_COMMIT: ${{ github.sha }}
          COVERALLS_GIT_BRANCH: ${{ github.ref }}
          COVERALLS_SERVICE_JOB_ID: ${{ github.run_id }}
          COVERALLS_PARALLEL: true
          CI_PULL_REQUEST: ${{ github.event_name == 'pull_request' && github.event.number || null }}
        with:
          timeout_minutes: 1 # Tests run for about 45s
          max_attempts: 3
          command: npm test

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Close parallel build
        uses: coverallsapp/github-action@v2
        with:
          parallel-finished: true
